import sys
import time
from playsound3 import playsound

def typewriter_effect(text, delay = 0.1):
    sys.stdout.write("\033[91m")
    for char in text:
        sys.stdout.write(char)
        sys.stdout.flush()
        time.sleep(delay)
    print()

def main():
    playsound("Scarface (Push It To The Limit) - Paul Engemann.mp3", block=False)

    typewriter_effect("As far back as I can remember I always wanted to be a gangster")
    typewriter_effect("......")
    typewriter_effect("To me...")
    typewriter_effect("Being a gangster was...better than being the president of the united states")
    typewriter_effect("In this country...you gotta make the money first...")
    typewriter_effect("Then you got the money...you get the power")
    typewriter_effect("Then you got the power....then you get the women")
    typewriter_effect("......")
    typewriter_effect("....")
    typewriter_effect("Lets get this straight now....")
    typewriter_effect("I never fucked anyone in my life that didnt have come to it")
    typewriter_effect("You got that?")
    typewriter_effect("........")
    typewriter_effect("All I have in this world...is my balls and my word and I dont break them for no one")
    typewriter_effect("That piece of shit up there I never liked him....I never trusted him")
    typewriter_effect("......")
    typewriter_effect("But that's history...Im here he's not")
    typewriter_effect("You wanna make a deal with me you say it....")
    typewriter_effect("......")
    typewriter_effect("If you dont?")
    typewriter_effect("Then you make a move")
    typewriter_effect("You tell him that Tony Montana is on his way up")
    typewriter_effect("The eyes chico....")
    typewriter_effect("They never lied")
    typewriter_effect("Me I want whats coming to me..")
    typewriter_effect("Well what was coming to you?")
    typewriter_effect("........")
    typewriter_effect("The World chico.....")
    typewriter_effect("And everything in it")
    typewriter_effect("Antonio....Montana")
    typewriter_effect("I kill communist for fun....")
    typewriter_effect("But for a green card")
    typewriter_effect("I gotta carve him up real good")
    typewriter_effect("I work hard for this....")
    typewriter_effect("You're all bunch of assholes you know....")
    typewriter_effect("You know why?")
    typewriter_effect("You dont have guts to be like me")
    typewriter_effect("......")
    typewriter_effect("You need people like me....")
    typewriter_effect("You need people like me so you can point your fucking finger and say...")
    typewriter_effect("That's the bad guy....")
    typewriter_effect("So what are you?....Good?")
    typewriter_effect("You're not good")
    typewriter_effect("You just know how to hide....how to lie...")
    typewriter_effect("............")
    typewriter_effect("...")
    typewriter_effect("So say goodnight to the bad guy")

if __name__ == "__main__":
    main()
